# Generated by Django 3.2.5 on 2021-07-19 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('bebida_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cliente_id', models.AutoField(primary_key=True, serialize=False)),
                ('identificacion', models.IntegerField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('direccion', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Cod_descuento',
            fields=[
                ('cod_descuento_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20)),
                ('porcentaje', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('dimension_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Galleta',
            fields=[
                ('galleta_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ingrediente_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('venta_id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('delivery', models.CharField(choices=[('S', 'Si'), ('N', 'No')], max_length=2)),
                ('metodo_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Pago Movil', 'PM'), ('Zelle', 'Zelle'), ('Tarjeta', 'Tarjeta')], max_length=15)),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.cliente')),
                ('galleta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.galleta')),
            ],
        ),
        migrations.CreateModel(
            name='Sandwich',
            fields=[
                ('sandwich_id', models.AutoField(primary_key=True, serialize=False)),
                ('dimension_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.dimension')),
                ('venta_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Contenido',
            fields=[
                ('contenido_id', models.AutoField(primary_key=True, serialize=False)),
                ('ingrediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.ingrediente')),
                ('sandwich_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.sandwich')),
            ],
        ),
        migrations.CreateModel(
            name='Combo',
            fields=[
                ('combo_id', models.AutoField(primary_key=True, serialize=False)),
                ('bebida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.bebida')),
                ('venta_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.venta')),
            ],
        ),
    ]
