# Generated by Django 3.2.5 on 2021-07-21 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandwich',
            name='bebida_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.bebida'),
        ),
        migrations.DeleteModel(
            name='Combo',
        ),
    ]
