# Generated by Django 3.2.5 on 2021-07-23 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210722_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='total',
            field=models.FloatField(),
        ),
    ]
