# Generated by Django 3.2.5 on 2021-07-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_venta_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bebida',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='dimension',
            name='precio',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='precio',
            field=models.FloatField(),
        ),
    ]
